loglevel: info
cpus: 1
monitoring:
  port: 5555
protocols:
  http:
    enable: true
    mocks_dir: "./mocks"
    port: 8080
origins:
  - http://localhost:3000
  - http://localhost:3001
  - http://localhost:5000
  - http://localhost:4200
  - http://localhost:4210
